### ISSUE TITLE
[10406] Causing Crash back to menu.

### ISSUE THREAD

**Issue by Helldrone** [Axema/Secronom-Zombies#11]
Hello! i recently updated from.
[10400] build to [10406] and i got this error!

![image](https://user-images.githubusercontent.com/49344129/76169570-ca3aa700-6179-11ea-979d-f5d9240d7133.png)

It crashes upon trying to load my save back to menu! anyway, thanks for checking!

**Comment by Axema** [comment]
The bugfix is coming :+1:
