### ISSUE TITLE
Download the mod here

### ISSUE THREAD

**Issue by Axema** [Axema/Secronom-Zombies#12]
I'm having a technical problem with my workplace so... Download the latest mod [here](https://cdn.discordapp.com/attachments/688147493850054794/703993701470306414/secronom.zip) for new contents and bug fixes :wink:

Mod version: V1.8 - 04/27/2020

By the month of May, I'll submit the official commits :heart:

**Comment by sayke** [comment]
I'm interested in submitting a PR with the minor tweaks and additions that I've added locally, but I'll wait till you update this repo with the new version and go from there.

Thank you for all your careful and creative thought on this! It really is an excellent mod.

**Comment by Axema** [comment]
Official commits submitted :ok_hand:

Might reopen this issue if I encounter a new problem...
