### ISSUE TITLE
Game stops after worldgen sending me back to main menu

### ISSUE THREAD

**Issue by 3NC3PH4L0ND1V3** [Axema/Secronom-Zombies#13]
Just loaded DDA core and your mod to get sure its not an issue another mod is causing. All other mods work as intended.

 DEBUG    : Error: line 85:28: no such item type 'anesthesia'

            ],
            "place_loot": [{
                    "item":
                           ^
                            "anesthesia",
                    "x": 16,
                    "y": [14, 17],

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 902

After exiting the game it crashes completely. Please look into this your mod is awesome ;)

**Comment by Axema** [comment]
It is fixed now :+1:
Redownload the mod in this [issue](https://github.com/Axema/Secronom-Zombies/issues/12)

**Comment by 3NC3PH4L0ND1V3** [comment]
Nice! You made my day!
