### ISSUE TITLE
Kicked back to main menu when trying to create a new character

### ISSUE THREAD

**Issue by Nitsua1230** [Axema/Secronom-Zombies#14]
Happens even when only dda and secronom are loaded and when using the download linked in the last issue. Cdda version 10492

 DEBUG    : Error: line 42:32: no such item type 'anesthesia'

      },
      "place_items": [ { "item": "record_patient", "x": 7, "y": 6, "chance": 50 } ],
      "place_loot": [ { "item":
                               ^
                                "anesthesia", "x": 16, "y": [ 14, 17 ], "chance": 75 } ],
      "computers": {
        "5": {

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 816

**Comment by Axema** [comment]
Try this link

**Comment by Axema** [comment]
Try this [link](https://cdn.discordapp.com/attachments/696145854880415834/696610036524253214/secronom.zip) :wink:
