### ISSUE TITLE
Secronom fails to load with the latest experimental build (10633)

### ISSUE THREAD

**Issue by Nephelos** [Axema/Secronom-Zombies#18]
Describe the bug

As the title says, it just throws me back to the menu.

![secrobug](https://user-images.githubusercontent.com/64908210/81183571-97613380-8faf-11ea-897c-cca099d9483f.png)

Steps to reproduce

1. Make a world with Secronom
2. Try to ignore/continue

Versions and Configuration

OS: Win 10 Enterprise N LTSC 17763
Game Version: 0.E-1826-g771188a
Graphics Version: Tiles (MSX++ UnDeadPeople)
Ingame language: English
Mods loaded: dda, secronom

**Comment by Phenomphear** [comment]
I found the solution earlier, 119 and a few lines below need to read as:
`{
        "text": "Nope. Bye.",
        "topic": "TALK_DONE",
        "condition": 
        {
          "and": [ { "not": { "u_has_effect": "secro_guard_partake_mission1" } }, { "u_has_effect": "secro_guard_mission1_progress" } ]
        }
      }
    ]
    },`

It's just some mistakes in the code. But I am also getting errors about damage using legacy methods. You can skip them and play, but, I have no idea what the effect will be on the gameplay.

**Comment by Nephelos** [comment]
Thanks i ll try that out until the official fix.

**Comment by Axema** [comment]
It was fixed earlier :wink: 
Please redownload the mod to apply the fix.
