### ISSUE TITLE
Separator error

### ISSUE THREAD

**Issue by SomeDeadGuy** [Axema/Secronom-Zombies#2]
Having this error on loading
![error](https://user-images.githubusercontent.com/37592026/54012979-c3550f00-4188-11e9-9d76-75311bf2339e.png)

**Comment by Axema** [comment]
Oh, sorry :3
I didn't test the mod before release, and didn't know this mistake :cry:

**Comment by Axema** [comment]
Fixed... Thanks BTW :)
