### ISSUE TITLE
Secronom crashes on 0.E Stable (10478)

### ISSUE THREAD

**Issue by Retoet** [Axema/Secronom-Zombies#20]
DEBUG    : Error: data/mods//secronom/Modification Files/secro_achievements.json: line 4:12: unrecognized JSON object

[
  {
    "id": "achievement_secronom_monkill_basictrio",
    "type":
           ^
            "achievement",
    "name": "<color_light_red>(Secronom)</color> The Basic Trio",
    "description": "Slay a blade zombie, a tendril zombie and a spider zombie.\n",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

I've tried updating the mod as the github page says but it keeps crashing whenever I try to create a new custom character.

**Comment by Axema** [comment]
Secronom is compatible only with the recent experimental builds, due to its usage of new functions such as achievements :3
