### ISSUE TITLE
Fleshed military bunkers corrupts the area

### ISSUE THREAD

**Issue by ads6465** [Axema/Secronom-Zombies#23]
Once you walk into the zone of a fleshed military bunker it will be normal and nothing is wrong (I have not gone inside).  If you try to go back to it already once leaving it will cause your game to crash making the area a no-go zone.  I was playing on the experimental's maybe about three week's old now.  This bug happened on various experimental versions with no other mods in use.

**Comment by Axema** [comment]
I tried to recreate the bug: I came to the fleshed bunker, then saved my game. It didn't show any crash logs.

Can you give me the screenshot of this bug? That might help :)

**Comment by ads6465** [comment]
I recreated a world to see if the issues is  happening and I cannot load a
world with version 0.E-4044-g05093fa.  I think there is something wrong
with my version of the mod maybe its not updated idk, Im going to try
reinstalling it.

**Comment by ads6465** [comment]
Ok there was something wrong with my copy of the mod,  after reinstalling
it it is working fine and I am not getting the crash anymore.  Sorry about
that!

**Comment by Axema** [comment]
Yes, the bug appears because you have an outdated mod. I made an issue about this in the [CDDA github](https://github.com/CleverRaven/Cataclysm-DDA/issues/41261) because there's a special item that spawned in bunker that generates an error when you load your savefile.
