### ISSUE TITLE
Outdated damage_type cause the game to crash upon loading a save or create a new world

### ISSUE THREAD

**Issue by technich214** [Axema/Secronom-Zombies#26]
Hello Axema. I encounter an issue in the latest build of the game experimental #10917. It seems that 
secro_magic.json
and secro_magic_trans.json
has outdated damage_type ("fire" instead of "heat", "bio" instead of "biological") which will crashed the game upon loading a new world or save.
I already have a working solution (just replaced the above mention tags). And i'm using it to play test a fresh game install and an existing game with 10+ mods.
BTW: i love your mods both secronom and vampiric things

**Comment by Axema** [comment]
Thanks for the solution, it is fixed now :+1:
