### ISSUE TITLE
Skittering Weaver crashes the game

### ISSUE THREAD

**Issue by Aphegis** [Axema/Secronom-Zombies#5]
Tested in a world with no mods, only secronom itself. When a skittering weaver gets within 2 tiles from the player, the game have a big chance of crashing (probably because he is trying to use his special attack?).

![no crash](https://user-images.githubusercontent.com/34956440/71417062-1b8ace00-2642-11ea-8a1c-d9f7481e2fed.PNG)

![crash](https://user-images.githubusercontent.com/34956440/71417063-1ded2800-2642-11ea-8b56-197871bc587e.PNG)

From the 6 times i tested, 5 crashed when he got closer than 2 tiles.

**Comment by Axema** [comment]
Hmmm... Maybe its the random spell targetting getting unknown results.
I'll fix it later!

**Comment by Axema** [comment]
[f8ff212](https://github.com/Axema/Secronom-Zombies/commit/f8ff2124cf59b89d0539af5cd36fab4d14815ca5) it is fixed ;)

**Comment by Axema** [comment]
Still gives an error. Maybe there's something I didn't notice 🤔

**Comment by Axema** [comment]
[f53f1d7](https://github.com/Axema/Secronom-Zombies/commit/f53f1d743095c77d7f8bfe2be58a09f1023f3acd) I think it is fixed now (playtested to make sure it doesn't appear again!)
