### ISSUE TITLE
color-related errors on world load

### ISSUE THREAD

**Issue by Kilvoctu** [Axema/Secronom-Zombies#7]
**Describe the bug**

Looks like a load of errors appearing upon loading world under newer CDDA experimentals

**Steps To Reproduce**

(Tested on CDDA build#10085 and #10089)
1. Create a world with Secronom active
2. Create character and load world

**Screenshots**
![1](https://user-images.githubusercontent.com/2993060/71564077-035ee880-2a60-11ea-9fa2-a06061949a85.PNG)
![2](https://user-images.githubusercontent.com/2993060/71564078-035ee880-2a60-11ea-86ee-cf2a22d10ccb.PNG)

Error also occurs for colors c_dark_blue and c_gray
See debug log for more
[debug.log](https://github.com/Axema/Secronom-Zombies/files/4008705/debug.log)

**Comment by ephemeralstoryteller** [comment]
Haha, I was just about to get around to this. These color syntax errors were technically always present but just quietly shunted into the debug.log in the past. Now they require dealing with the prompts, as of [this change](https://github.com/CleverRaven/Cataclysm-DDA/pull/36433) in build 10085. You can safely ignore all of them, though it might take a moment of holding down spacebar. 

I'll have a PR correcting the issues in a moment.

**Comment by Kilvoctu** [comment]
Yeah, figured it had something to do with build 10085 when I looked through its changes. Was gonna report it last night, but figured I'd wait a bit to see if the issue's resolved. Guess I should have waited a little longer, heh. :)

**Comment by ephemeralstoryteller** [comment]
No problem! Reporting a bug only to find out that a wayward code monkey already had her sights on it is hardly the worst thing in the world. ^^

**Comment by Axema** [comment]
I didn't know the source of this bug until I see ephemeral's fix. I once tried searching for `c_dark_red` on my entire mod folder, but unfortunately it came up with nothing.

And yeah, the recent commit fixed the error :+1:

**Comment by Kilvoctu** [comment]
Yeah, did the same when I searched your mod folder (thanks, dnGrep, for making it easy), but had more success when I searched for just `"dark_red"`.  
I hacked together a solution for myself for the night, but the gibberish error from first screenshot persisted. Thank you both for you work. I've always enjoyed this mod for adding a lot of flavor but not going _too_ crazy with it :+1:
